export const item = {
    "id": "538a543e-7cc9-4a66-9f21-4d214ce3a9d9",
    "profile_text": "account",
    "share_icon": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/289.png",
    "setting_icon": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/341.png",
    "profile_icon": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/181.png",
    "name": "hear",
    "profile_id": "world",
    "total_text": "majority",
    "total": "former",
    "average_text": "concern",
    "average": "position",
    "location_icon": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/253.png",
    "addres": "walk",
    "ful_add": "group",
    "right_arrow": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/22.png",
    "language_icon": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/69.png",
    "language_text": "world",
    "lang_qwerty": "physical",
    "visit_language": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/113.png",
    "log_out_icon": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/222.png",
    "log_out_text": "course",
    "visit_logout": "https://the-coder.s3.ap-south-1.amazonaws.com/images_540/233.png"
}